# Generated by Django 3.2.16 on 2024-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20240403_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplications',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('selected', 'selected')], default='pandding', max_length=20),
        ),
    ]
