# Generated by Django 3.2.16 on 2024-04-04 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0002_alter_myapplyjoblist_job_alter_myapplyjoblist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapplyjoblist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
