# Generated by Django 5.0.6 on 2024-07-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_job_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job_company',
        ),
    ]
